minimalqa/config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resource :favorites, only: [:create, :destroy]
      resources :answers, shallow: true do
        resources :reactions, only: [:new, :create]
      end
    end

  resources :users, only: [:index, :new, :create, :show] do
    get :favorites, on: :collection
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'sessions/:id' => 'sessions#destroy'
  root 'users#home'
end

minimalqa/app/models/answer.rb
class Answer < ApplicationRecord
  validates :body, presence: true, length: { maximum: 300 }
  belongs_to :user
  belongs_to :question
  has_many :reactions, dependent: :destroy
end

minimalqa/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

minimalqa/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates_uniqueness_of :question_id, scope: :user_id
end

minimalqa/app/models/question.rb
class Question < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 250 }
  belongs_to :user
  has_many :answers, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

minimalqa/app/models/reaction.rb
class Reaction < ApplicationRecord
  validates :body, presence: true, length: { maximum: 140 }
  belongs_to :user
  belongs_to :answer
end

minimalqa/app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 8 }
    has_secure_password validations: true

    has_many :questions, dependent: :destroy
    has_many :favorites, dependent: :destroy
end

minimalqa/app/controllers/answers_controller.rb
class AnswersController < ApplicationController
    before_action :logged_in_user
    
    def create
        if @question = Question.find(params[:question_id])
            @question.answers.create(answer_params)
            redirect_to question_path(@question)
        else
            render "questions/show"
        end
    end

    private
    def answer_params
        params.require(:answer).permit(:user_id, :question_id, :body)
    end
end

minimalqa/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include SessionsHelper
    before_action :set_search

    def set_search
        @q = Question.ransack(params[:q])
        @questions = @q.result.page(params[:page]).order(created_at: "DESC")
    end

    private
    def logged_in_user
      unless logged_in?
        redirect_to new_session_path
      end
    end
end

minimalqa/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    before_action :set_favorite
    before_action :logged_in_user

    def create
        if @question.user_id != current_user.id
          @favorite = Favorite.create(user_id: current_user.id, question_id: @question.id)
        end
    end

    def destroy
        @favorite = Favorite.find_by(user_id: current_user.id, question_id: @question.id)
        @favorite.destroy
    end
    
    private
    def set_favorite
        @question = Question.find(params[:question_id])
    end
end

minimalqa/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: %i[ edit ]

  def index
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)

    respond_to do |format|
      @question.user_id = current_user.id
      if @question.save
        format.html { redirect_to question_url(@question), notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to question_url(@question), notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:user_id, :title, :body, :bestanswer_id)
    end
end

minimalqa/app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :logged_in_user

  def new
    answer = Answer.find(params[:answer_id])
    @reaction = answer.reactions.build(user_id: current_user.id)
  end

  def create
    answer = Answer.find(params[:answer_id])
    @reaction = answer.reactions.build(reaction_params)

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to question_path(answer.question_id), notice: "Reaction was successfully created." }
        format.json { render :show, status: :created, location: @reaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def reaction_params
      params.require(:reaction).permit(:user_id, :answer_id, :body)
    end
end

minimalqa/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
   
    def create
      user = User.find_by(name: params[:session][:name].downcase)
      if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id
        redirect_to questions_path
      else
        flash[:alert] = "※ ユーザー名またはパスワードが間違っています"
        render 'new'
      end
    end
   
    def destroy
      session.delete(:user_id)
      redirect_to new_session_path
    end
end

minimalqa/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only:[:index, :show]

  def home
  end

  def new
      @user = User.new
  end

  def index
      @questions = current_user.questions.all.order(created_at: :desc).page(params[:page])
  end

  def show
      @user = User.find(params[:id])
      @question = @user.questions

      favorites = Favorite.where(user_id: current_user.id).pluck(:question_id)
      @favorite_list = Question.find(favorites)
  end
   
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to new_session_path
      else
        render 'new'
      end
    end
   
    private
    
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

minimalqa/app/helpers/answers_helper.rb
module AnswersHelper
end

minimalqa/app/helpers/application_helper.rb
module ApplicationHelper
end

minimalqa/app/helpers/fovorites_helper.rb
module FovoritesHelper
end

minimalqa/app/helpers/questions_helper.rb
module QuestionsHelper
end

minimalqa/app/helpers/reactions_helper.rb
module ReactionsHelper
end

minimalqa/app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
     
    def logged_in?
        current_user.present?
    end
end

minimalqa/app/helpers/users_helper.rb
module UsersHelper
end

minimalqa/app/views/favorites/_favorite.html.erb
<% if Favorite.exists?(user: current_user, question_id: @question.id) %>
    <%= link_to question_favorites_path(@question), method: :delete, remote: true do %>
        <i class="bi bi-bookmark-heart"></i>
    <% end %>
    <%= @question.favorites.length %>
<% else %>
    <%= link_to question_favorites_path(@question), method: :post, remote: true do %>
        <i class="bi bi-bookmark-heart-fill"></i>
    <% end %>
    <%= @question.favorites.length %>
<% end %>

minimalqa/app/views/favorites/create.js.erb
$("#favorite_<%= @question.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { question: @question }) %>");

minimalqa/app/views/favorites/destroy.js.erb
$("#favorite_<%= @question.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { question: @question }) %>");

minimalqa/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minimalqa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_packs_with_chunks_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_packs_with_chunks_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>
<div class="container">
  <div class="row">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <%= image_tag 'logo.png', class: "navbar-brand bg-dark col-xs-2", size: '60x60' %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item col-xs-1">
          <%= link_to("ホーム", root_path, {class: "nav-link bg-dark"}) %>
        </li>
        <li class="nav-item col-xs-1">
          <%= link_to("みんなの質問", questions_path, {class: "nav-link bg-dark"}) %>
        </li>
      <% if logged_in? %>
        <li class="nav-item col-xs-1">
          <%= link_to("マイページ", users_path, {class: "nav-link bg-dark"}) %>
        </li>
        <li class="nav-item col-xs-1">
          <%= link_to("お気に入り", user_path(@current_user.id), {class: "nav-link bg-dark"}) %>
        </li>
        <li class="nav-item col-xs-1">
          <%= link_to("ログアウト", session_path(current_user.id), class: "nav-link bg-dark", method: :delete) %>
        </li>
        <li class="nav-item col-xs-1">
          <%= link_to("質問する!", new_question_path, {class: "btn btn-success text-light"}) %>
        </li>
      <% end %>
      </ul>
      <%= search_form_for @q, url: questions_path do |f| %>
      <div class="d-flex">
        <%= f.search_field :title_or_body_cont, class: "form-control me-2 col-xs-2", placeholder: "検索" %>
        <%= f.submit "検索", class: "btn btn-success col-xs-2" %>
      </div>
      <% end %>
    </div>
  </div>
</nav>
</div>
</div>
    <%= yield %>
  <footer class="fixed-bottom" class="bg-dark text-center text-lg-start">
  <div class="text-center p-3 text-white-50" style="background-color: rgba(0, 0, 0, 1);">
    © 2022 ミニマルQA
  </div>
</footer>
</body>
</html>

minimalqa/app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
<div class="mb-3">
  <%= form.label :title, "タイトル（20字以内）", class: "form-label", for: "validationServer03" %>
  <%= form.text_field :title, class: "form-control form-control-lg" %>
</div>
<div class="mb-3">
  <%= form.label :body, "内容（250字以内）", class: "form-label" %>
  <%= form.text_area :body, class: "form-control form-control-lg", rows: "5" %>
</div>
  <div class="d-grid gap-2 col-lg mx-auto mb-3">
    <%= form.submit "投稿", class: "btn btn-success" %>
  </div>
<% end %>

minimalqa/app/views/questions/edit.html.erb
<div class="text-center pt-5">
<h1 class="h3 mb-5 fw-normal mt-5">質問編集</h1>
<% if @question.errors.any? %>
<div class="text-danger mb-4">
    ※ 空、もしくは指定の文字数を超えています。
</div>
<% end %>
<div class="card mx-auto text-center w-50">
    <div class="card-body">

<%= render 'form', question: @question %>

</div>
</div>
</div>

<div class="text-center">
    <%= link_to '戻る', @question, class: "btn btn-outline-success text-dark mt-5" %>
</div>

minimalqa/app/views/questions/index.html.erb
<main class="pb-5 pt-5">
<div class="text-center mt-5 mb-5">
  <h1>みんなの質問</h1>
</div>
<div class="card text-center mx-auto w-50">
<% @questions.each do |question| %>
  <div class="card-header">
  <% if question.bestanswer_id == nil %>
    <button type="button" class="btn btn-secondary btn-lg" disabled>未解決</button>
  <% else %>
    <button type="button" class="btn btn-primary btn-lg" disabled>解決済み</button>
  <% end %>
  </div>
  <div class="card-body">
    <h5 class="card-text"><%= question.user.name %>さんの質問</h5>
    <h2 class="card-title">タイトル :　<%= question.title %></h2>
    <%= link_to("詳しく見る", question, {class: "btn btn-success text-light"}) %>
  </div>
  <div class="card-footer text-muted mb-5">
    <%= time_ago_in_words(question.created_at) %>前
  </div>
<% end %>
  </div>
  <div class="mt-5 mb-5">
  </div>
      <%= paginate @questions %>
  <div class="mt-5 mb-5">
  </div>
</main>

minimalqa/app/views/questions/new.html.erb
<div class="text-center pt-5">
<h1 class="h3 mb-5 fw-normal mt-5">質問作成</h1>

<% if @question.errors.any? %>
<div class="text-danger mb-4">
    ※ 空、もしくは指定の文字数を超えています。
</div>
<% end %>

<div class="card mx-auto text-center w-50">
    <div class="card-body">

<%= render 'form', question: @question %>

    </div>
</div>
</div>

minimalqa/app/views/questions/show.html.erb
 <main class="mb-5">
  <div class="mt-5 mb-5">
  </div>
<div class="pt-5 pb-5 text-center">
  <h1><%= @question.user.name %>さんの質問</h1>
</div>
<div class="card mb-3 w-50 mx-auto">
  <div class="card-body">
    <h3 class="card-title">タイトル : <%= @question.title %></h3>
    <h5 class="mt-4">内容 :</h5>
    <h4 class="card-text"><%= @question.body %></h4>
    <div class="card-text mt-4"><small class="text-muted">
      <%= time_ago_in_words(@question.created_at) %>前</small>
    </div>
    <div class="card-text text-end" id="favorite_<%= @question.id %>">
      <%= render partial: 'favorites/favorite', locals: {question: @question} %>
    </div>
  </div>
</div>

<% if logged_in? %>
<% if @question.user_id == current_user.id %>
  <div class="text-center">
    <%= link_to "編集する", edit_question_path(@question), class: "btn btn-success text-white" %>
    <%= link_to "削除する", @question, class: "btn btn-danger text-white", method: :delete %>
  </div>
<% end %>
<% end %>

<% if @question.answers.any? %>
<div class="pt-5 pb-5 text-center">
  <h1>回答一覧</h1>
</div>
<div class="card mb-3 w-50 mx-auto">
<% @question.answers.each do |answer| %>
  <div class="card-body">
    <div class="card-title mb-4 btn btn-secondary">
      <%= answer.user.name %>さんの回答
    </div>
    <% if logged_in? %>
    <% if @question.bestanswer_id == answer.id %>
      <span class="badge bg-primary">ベストアンサー</span>
    <% end %>
    <% end %>
    <h5>回答 :</h5>
    <%= auto_link(simple_format(h(answer.body), target: :_blank, rel: "noopener noreferrer", class: "card-text h4")) %>
    <div class="card-text mt-4"><small class="text-muted">
      <%= time_ago_in_words(answer.created_at) %>前</small>
    </div>
    <% answer.reactions.each do |reaction| %>
      <div class="card-title mt-5 mb-4 btn btn-secondary">
        <%= reaction.user.name %>さんのリアクション
      </div>
      <h5>内容 :</h5>
      <h4 class="card-text"><%= auto_link(simple_format(h(reaction.body), target: :_blank, rel: "noopener noreferrer", class: "card-text h4")) %></h4>
      <div class="card-text mt-4"><small class="text-muted">
        <%= time_ago_in_words(reaction.created_at) %>前</small>
      </div>
    <% end %>
    <% if logged_in? %>
    <% if @question.bestanswer_id == nil %>
      <div class="card-text text-end">
        <%= link_to 'リアクションする', new_answer_reaction_path(answer.id), class: "btn btn-success text-white" %>
      </div>
    <% end %>
    <% end %>
    <% if logged_in? %>
    <% if @question.user_id == current_user.id %>
    <%= form_with(model: @question, local: true, data: {confirm: "ベストアンサーにします、修正はできませんがよろしいですか？"}) do |f| %>
      <%= f.hidden_field :bestanswer_id, value: answer.id %>
      <div class="card-text text-end">
        <%= f.submit 'ベストアンサー', disabled: @question.bestanswer_id.present?, class: "btn btn-danger mt-4" %>
      </div>
    <% end %>
    <% end %>
    <% end %>
    </div>
    <% end %>
  </div>
    <% else %>
    <div class="pt-5 pb-5 text-center">
      <h1>回答がありません</h1>
    </div>
    <% end %>

  <% if logged_in? %>
  <% if @question.user.id != current_user.id && @question.bestanswer_id == nil %>
    <div class="text-center pt-5">
      <h1 class="mb-5 fw-normal mt-5">回答する</h1>
    <div class="card mx-auto text-center w-50">
      <div class="card-body">
    <%= form_with model: [@question, @question.answers.build] do |f| %>
      <div class="mb-3">
        <%= f.label :body, "内容（300字以内）", class: "form-label" %>
        <%= f.text_area :body, class: "form-control form-control-lg", rows: "6" %>
      </div>
      <%= f.hidden_field :question_id, value: @question.id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <div class="d-grid gap-2 col-lg mx-auto mb-3">
        <%= f.submit "回答", disabled: @question.bestanswer_id.present?, class: "btn btn-success" %>
      </div>
    <% end %>
  <% end %>
  <% end %>
      </div>
  </div>
  </div>
  <div class="pb-5 pt-5 text-center">
    <%= link_to "質問一覧に戻る", questions_path, class: "btn btn-outline-success text-dark" %>
  </div>

  </main>

minimalqa/app/views/reactions/_form.html.erb
<%= form_with(model: reaction, url: answer_reactions_path(@reaction.answer.id), local: true) do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
    <div class="mb-3">
      <%= form.label :body, "内容（300字以内）", class: "form-label" %>
      <%= form.text_area :body, class: "form-control form-control-lg", rows: "7" %>
    </div>
    <div class="d-grid gap-2 col-lg mx-auto mb-3">
      <%= form.submit "作成", class: "btn btn-success" %>
    </div>
<% end %>

minimalqa/app/views/reactions/new.html.erb
<div class="text-center pt-5">
    <h1 class="h3 mb-5 fw-normal mt-5">コメント作成</h1>
    <% if @reaction.errors.any? %>
    <div class="text-danger mb-4">
        ※ 空、もしくは指定の文字数を超えています。
    </div>
    <% end %>
        <div class="card mx-auto text-center w-50 border-dark">
            <div class="card-body">
                <%= render 'form', reaction: @reaction %>
            </div>
        </div>
    <%= link_to "詳細画面に戻る", question_path(@reaction.answer.question.id), class: "btn btn-outline-success text-dark mt-5" %>
</div>

minimalqa/app/views/users/home.html.erb
<%= image_tag 'home.png', class: "d-block w-100 opacity-50 col-xs-12" %>
<div class="title fixed-top text-dark text-center">
    <h1>ミニマルQAとは</h1>
    <p>-------------------------------------------------------</p>
    <h3 class="mt-5 mb-5">ミニマリストになりたいあなたを支えるQ&Aサイトです</h3>
    <% if logged_in? %>
    <% else %>
<div class="container">
    <div class="row">
    <div class="d-grid gap-2 col-3 mx-auto">
        <%= link_to("新規登録", new_user_path, {class: "btn btn-success btn-lg text-light mb-5"}) %>
        <%= link_to("ログイン", new_session_path, {class: "btn btn-success btn-lg text-light"}) %>
    </div>
    </div>
</div>
    <% end %>
</div>

minimalqa/app/views/users/index.html.erb
<main class="pb-5 pt-5">
<div class="text-center mt-5 mb-5">
  <h1><%= current_user.name %>さんの質問一覧</h1>
</div>
<div class="card text-center mx-auto w-50">
<% if @questions.any? %>
<% @questions.each do |question| %>
  <div class="card-header">
  <% if question.bestanswer_id == nil %>
    <button type="button" class="btn btn-secondary btn-lg" disabled>未解決</button>
  <% else %>
    <button type="button" class="btn btn-primary btn-lg" disabled>解決済み</button>
  <% end %>
  </div>
  <div class="card-body">
    <h2 class="card-title">タイトル : <%= question.title %></h2>
    <%= link_to("詳しく見る", question, {class: "btn btn-success text-light"}) %>
  </div>
  <div class="card-footer text-muted mb-5">
    <%= time_ago_in_words(question.created_at) %>前
  </div>
<% end %>
</div>
<div class="mt-5 mb-5">
  <%= paginate @questions %>
</div>
<% else %>
    <div class="pt-5 pb-5">
        <h3>過去の質問がありません</h3>
        <%= link_to("質問する！", new_question_path, {class: "btn btn-success text-white mt-4"}) %>
    </div>
<% end %>
</main>

minimalqa/app/views/users/new.html.erb
<body class="text-center pt-5">
<main class="form-signin">
      <h1 class="h3 mb-5 fw-normal mt-5">新規登録</h1>
      <% if @user.errors.any? %>
      <div class="text-danger mb-4">
          ※ 空、もしくは指定の文字数を超えています。
      </div>
      <% end %>
      <div class="card" style="width: 18rem;">
        <div class="card-body">
      <%= form_with(model: @user, local: true) do |f| %> 
      <div class="form-floating">
        <%= f.text_field :name, class: "form-control", placeholder: "名前(8文字以内)" %>
        <%= f.label :name, "名前(8文字以内)", class: "text-black-50", for: "floatingInputInvalid" %>
      </div>
      <div class="form-floating">
        <%= f.password_field :password, class: "form-control", placeholder: "パスワード" %>
        <%= f.label :password, "パスワード", class: "text-black-50", for: "floatingInput" %>
      </div>
      <div class="form-floating">
        <%= f.password_field :password_confirmation, class: "form-control", placeholder: "パスワード確認" %>
        <%= f.label :password_confirmation, "パスワード確認", class: "text-black-50", for: "floatingInput" %>
      </div>
      <%= f.submit "新規登録", class: "w-100 btn btn-lg btn-success mt-5" %>
      <% end %>
      </div>
      </div>
</main>
<div class="gap-2 col-3 mx-auto mt-5">
もしくは
<%= link_to("ログイン", new_session_path, {class: "btn btn-success text-light"}) %>
</div>
</body>

minimalqa/app/views/users/show.html.erb
<main class="pb-5 pt-5">
<div class="text-center mt-5 mb-5">
  <h1><%= current_user.name %>さんのお気に入り</h1>
</div>
<div class="card text-center mx-auto w-50">
<% if @favorite_list.present? %>
    <% @favorite_list.each do |question| %>
        <div class="card-header">
            <% if question.bestanswer_id == nil %>
                <button type="button" class="btn btn-secondary btn-lg" disabled>未解決</button>
            <% else %>
                <button type="button" class="btn btn-primary btn-lg" disabled>解決済み</button>
            <% end %>
        </div>
        <div class="card-body">
            <h5 class="card-text"><%= question.user.name %>さんの質問</h5>
            <h2 class="card-title">タイトル :　<%= question.title %></h2>
            <%= link_to("詳しく見る", question, {class: "btn btn-success text-light"}) %>
        </div>
        <div class="card-footer text-muted mb-5">
            <%= time_ago_in_words(question.created_at) %>前
        </div>
    <% end %>
<% else %>
    <div class="pt-5 pb-5">
        <h3>お気に入りはありません</h3>
        <%= link_to("探しに行く", questions_path, {class: "btn btn-success text-white"}) %>
    </div>
<% end %>
    </div>  
</main>